version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: roda-portal
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      STAGE: 'local'
      DOMAINS: "minus-y.com -> http://dockerhost:1080"
    volumes:
      - "./https/ssl:/var/lib/https-portal"
    networks:
      - default
      - web_default
networks:
  web_default:
    external: true

