services:
  web:
    build:
      context: local/nginx
      dockerfile: "Dockerfile"
    volumes:
      - "./app/public:/var/www/html/public"
      - "./app/storage/app/public/up:/var/www/up"
    env_file:
      .env
    links:
      - app
    ports:
      - 127.0.0.1:3080:80
    networks:
      - uproda-proxy-network

  app:
    build:
      context: local/php
      dockerfile: "Dockerfile"
    volumes:
      - ./app:/var/www/html
    links:
      - db-primary
      - db-secondary
      - redis
    networks:
      - default
      - uproda-proxy-network

  db-primary:
    image: mariadb:10.5
    env_file:
      - .env
    ports:
      - 127.0.0.1:33306:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./db/init/primary.sh:/docker-entrypoint-initdb.d/primary.sh
      - ./db/cnf/primary.cnf:/etc/mysql/conf.d/my.cnf

  db-secondary:
    image: mariadb:10.5
    env_file:
      - .env
    ports:
      - "127.0.0.1:53316:3306"

  db-test:
    image: mariadb:10.5
    env_file:
      - .env
    ports:
      - 127.0.0.1:33307:3306

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:36379:6379
    command: redis-server

  storage:
    # docker pull minio/minio:RELEASE.2022-10-29T06-21-33Z
    # docker pull minio/minio:RELEASE.2022-10-08T20-11-00Z.fips
    # image: minio/minio:RELEASE.2022-10-08T20-11-00Z.fips
    image: minio/minio
    ports:
      - "29000:9000"
      - "29001:9001"
    volumes:
      - ".data/minio:/export"
    env_file:
      - .env
    command: "server /export --console-address :9001"
    networks:
      - default
      - uproda-proxy-network

networks:
  uproda-proxy-network:
    external: true
