version: '2'
services:
  roda-proxy:
    build:
      context: nginx
      dockerfile: "Dockerfile"
    links:
      - "php"
    ports:
      - "1080:80"
    restart: always
    volumes:
      - "./roda/public:/var/www/roda/"

  php:
    build:
      context: php
      dockerfile: "Dockerfile"
    restart: always
    volumes:
      - "./roda:/var/www/roda/"
    links:
      - "db"
      - "redis"

  db:
    build:
      context: db
      dockerfile: "Dockerfile"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "53306:3306"
  redis:
    build:
      context: .
      dockerfile: "./redis/Dockerfile"
    hostname: "roda-redis"
    ports:
      - "26379:6379"
    command: redis-server --appendonly yes --requirepass warecoli
