version: '2'
services:
  proxy:
    image: nginx:alpine
    volumes:
      - "./app/public:/var/www/html/public"
      - "./local/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - app
    ports:
      - 127.0.0.1:3080:80

  app:
    build:
      context: local/php
      dockerfile: "Dockerfile"
    volumes:
      - ./app:/var/www/html
    links:
      - db-primary
      - redis

  db-primary:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_DATABASE: uproda
      DB_USERNAME: uproda_user
      DB_PASSWORD: 1Qazxsw23edcvfR4
    ports:
      - 127.0.0.1:33306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  db-test:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_DATABASE: uproda
      DB_USERNAME: uproda_user
      DB_PASSWORD: 1Qazxsw23edcvfR4
    ports:
      - 127.0.0.1:33307:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:36379:6379
    command: redis-server
