version: '2'
services:
  web:
    build: ./nginx
    ports:
      - "1080:80"
      - "1443:443"
    restart: always
    volumes:
      - "./php/web:/var/www/roda/"
  php:
    build: ./php
    hostname: "roda-web"
    volumes:
      - "./php/web:/var/www/roda/"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:roda-db"
      - "redis:roda-redis"
      - "memcached:roda-memcached"
  db:
    build: ./db
    hostname: "roda-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    mem_limit: 1000000000
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "23306:3306"
  redis:
    build: ./redis
    hostname: "roda-redis"
    restart: always
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  memcached:
    build: ./memcached
    hostname: "roda-memcached"
    restart: always
    ports:
      - "11211:11211"
