#!/bin/sh
export MYSQL_PWD=$MYSQL_ROOT_PASSWORD
mysql -uroot -e "CREATE USER ${DB_USERNAME} IDENTIFIED BY '${DB_PASSWORD}';"
mysql -uroot -e "GRANT SELECT, INSERT, DELETE, UPDATE on ${MYSQL_DATABASE}.* to ${DB_USERNAME};"
