<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.5.3(314)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateImageTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('images', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();
            $table->bigInteger('image_hash_id')->nullable()->comment('image_hash.id');
            $table->string('basename', 100);
            $table->string('ext', 10)->nullable();
            $table->string('t_ext', 10)->nullable()->default('jpg');
            $table->string('original', 100)->nullable();
            $table->string('delkey', 20)->nullable();
            $table->string('mimetype', 20)->nullable();
            $table->integer('size')->nullable();
            $table->text('comment')->nullable();
            $table->string('ip', 40)->nullable();
            $table->dateTime('created_at')->useCurrent()->index();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('images');
    }
}
