<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.2(358)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateDenyIpsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('deny_ips', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();
            $table->string('ip', 40)->nullable()->default(null);
            $table->dateTime('created_at')->useCurrent()->index();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('deny_ips');
    }
}
