version: '2'
services:
  roda-proxy:
    build:
      context: nginx
      dockerfile: "Dockerfile"
    environment:
      - VIRTUAL_HOST=nejitsu.minus-y.com
    container_name: "roda-proxy"
    links:
      - "php"
    ports:
      - "127.0.0.1:1080:80"
    restart: always
    volumes:
      - "./app:/var/www/roda/"
    networks:
      - default
      - uproda-proxy-network 
  php:
    build:
      context: php
      dockerfile: "Dockerfile"
    hostname: "roda-web"
    restart: always
    volumes:
      - "./app:/var/www/roda/"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:roda-db"
      - "redis:roda-redis"
      - "memcached:roda-memcached"
  db:
    build:
      context: db
      dockerfile: "Dockerfile"
    hostname: "roda-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:53306:3306"
  redis:
    build:
      context: .
      dockerfile: "./redis/Dockerfile"
    hostname: "roda-redis"
    restart: always
    volumes:
      - "./redis/data:/data"
    ports:
      - "127.0.0.1:16379:6379"
    command: redis-server --requirepass warecoli

  memcached:
    build:
      context: .
      dockerfile: "./memcached/Dockerfile"
    hostname: "roda-memcached"
    restart: always
    ports:
      - "127.0.0.1:11211:11211"

networks:
  uproda-proxy-network:
    external: true
