version: '2'
services:
  roda-proxy:
    image: nginx:latest
    env_file:
      .env
    container_name: "roda-proxy"
    links:
      - "php"
    ports:
      - "127.0.0.1:1080:80"
    restart: always
    volumes:
      - "./app:/var/www/roda/"
      - "./nginx/etc/default.conf:/etc/nginx/templates/default.conf.template"
    networks:
      - default
      - uproda-proxy-network 

  php:
    build:
      context: php
      dockerfile: "Dockerfile"
    hostname: "roda-web"
    restart: always
    env_file:
      .env
    volumes:
      - "./app:/var/www/roda/"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:roda-db"
      - "redis:roda-redis"
      - "memcached:roda-memcached"

  db:
    image: ${IMAGE_DB}
    hostname: "roda-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:53306:3306"

  redis:
    image: redis:latest
    hostname: "roda-redis"
    restart: always
    ports:
      - "127.0.0.1:16379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  memcached:
    image: memcached:latest
    hostname: "roda-memcached"
    restart: always
    ports:
      - "127.0.0.1:11211:11211"

networks:
  uproda-proxy-network:
    external: true
