version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: roda-portal
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - "web:roda-web"
    environment:
      STAGE: 'local'
      DOMAINS: "minus-y.com -> http://roda-web:1080"
    volumes:
      - "./app:/var/www/roda/"
      - "./app:/var/www/vhosts/minus-y.com"
      - "./nginx/ssl:/var/lib/https-portal"
  web:
    build:
      context: nginx
      dockerfile: "Dockerfile"
    ports:
      - "1080:80"
    restart: always
    volumes:
      - "./app:/var/www/roda/"
      - "./app:/var/www/vhosts/minus-y.com"
  php:
    build:
      context: php
      dockerfile: "Dockerfile"
    hostname: "roda-web"
    volumes:
      - "./app:/var/www/roda/"
      - "./app:/var/www/vhosts/minus-y.com"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:roda-db"
      - "redis:roda-redis"
      - "memcached:roda-memcached"
  db:
    build:
      context: db
      dockerfile: "Dockerfile"
    hostname: "roda-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "23306:3306"
  redis:
    build:
      context: .
      dockerfile: "./redis/Dockerfile"
    hostname: "roda-redis"
    restart: always
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  memcached:
    build:
      context: .
      dockerfile: "./memcached/Dockerfile"
    hostname: "roda-memcached"
    restart: always
    ports:
      - "11211:11211"
