version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - "roda-proxy"
    environment:
      STAGE: 'local'
      DOMAINS: "nejitsu.minus-y.co.jp-> http://roda-proxy, minus-y.co.jp -> http://roda-proxy"
      CLIENT_MAX_BODY_SIZE: 20M
    volumes:
      - "./nginx/ssl:/var/lib/https-portal"
  roda-proxy:
    build:
      context: nginx
      dockerfile: "Dockerfile"
    container_name: "roda-proxy"
    links:
      - "php"
    ports:
      - "1080:80"
    restart: always
    volumes:
      - "./app:/var/www/roda/"
  php:
    build:
      context: php
      dockerfile: "Dockerfile"
    hostname: "roda-web"
    volumes:
      - "./app:/var/www/roda/"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:roda-db"
      - "redis:roda-redis"
      - "memcached:roda-memcached"
  db:
    build:
      context: db
      dockerfile: "Dockerfile"
    hostname: "roda-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4rfvcde3
      MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d"
    ports:
      - "53306:3306"
  redis:
    build:
      context: .
      dockerfile: "./redis/Dockerfile"
    hostname: "roda-redis"
    restart: always
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  memcached:
    build:
      context: .
      dockerfile: "./memcached/Dockerfile"
    hostname: "roda-memcached"
    restart: always
    ports:
      - "11211:11211"
